FROM node:10.16.0
RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
#COPY . /app
COPY package.json .

#RUN apk add tzdata
#RUN cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime
#RUN echo "Asia/Seoul" >  /etc/timezone
#RUN apk del tzdata

# RUN npm install pm2 -g

RUN npm install --silent
COPY . ./
EXPOSE 3000
CMD ["npm", "run", "start:staging" ]

# CMD ["pm2-runtime", "pm2-start.json", "--env", "production"]
