// Home Page
export const TAGS_SET_REQUEST = "TAGS_SET_REQUEST";
export const TAGS_SET_SUCCESS = "TAGS_SET_SUCCESS";
export const TAGS_SET_FAILURE = "TAGS_SET_FAILURE";

// Search Page
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS";
export const SEARCH_REQUEST_FAILURE = "SEARCH_REQUEST_FAILURE";
export const SELECTED_TAB = "SELECTED_TAB";
export const GET_AREA_REQUEST = "GET_AREA_REQUEST";
export const GET_MEDICAL_DEPARTMENT_REQUEST = "GET_MEDICAL_DEPARTMENT_REQUEST";
export const GET_MEDICAL_UNIVERSITIE_REQUEST =
    "GET_MEDICAL_UNIVERSITIE_REQUEST";
export const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";

export const SEARCH_AJAX = "SEARCH_AJAX";
export const SET_CNT_TOTAL = "SET_CNT_TOTAL";

export const FILTER_APPLY = "FILTER_APPLY";
export const FILTER_CLEAR = "FILTER_CLEAR";

// Doctor Promise
export const SET_DOCTOR_LIST = "SET_DOCTOR_LIST";
export const ADD_DOCTOR_LIST = "ADD_DOCTOR_LIST";
export const RMV_DOCTOR_LIST = "RMV_DOCTOR_LIST";

export const SELECTED_DOCTOR = "SELECTED_DOCTOR";
export const SELECTED_DOCTOR_SUCCESS = "SELECTED_DOCTOR_SUCCESS";
export const SELECTED_DOCTOR_FAILURE = "SELECTED_DOCTOR_FAILURE";

export const DOCTOR_AREA_FILTER_APPLY = "DOCTOR_AREA_FILTER_APPLY";
export const DEPARTMENT_FILTER_APPLY = "DEPARTMENT_FILTER_APPLY";
export const UNIVERSITIE_FILTER_APPLY = "UNIVERSITIE_FILTER_APPLY";

export const DOCTOR_FILTER_CLEAR = "DOCTOR_FILTER_CLEAR";

export const GET_DOCTOR_ALL_REVIEW = "GET_DOCTOR_ALL_REVIEW";

export const ADD_DOCTOR_PAPERS = "ADD_DOCTOR_PAPERS";

// Hospital Promise
export const SET_HOSPITAL_STATE = "SET_HOSPITAL_STATE";

export const SET_HOSPITAL_LIST = "SET_HOSPITAL_LIST";
export const ADD_HOSPITAL_LIST = "ADD_HOSPITAL_LIST";
export const RMV_HOSPITAL_LIST = "RMV_HOSPITAL_LIST";

export const SELECTED_HOSPITAL = "SELECTED_HOSPITAL";
export const SELECTED_HOSPITAL_SUCCESS = "SELECTED_HOSPITAL_SUCCESS";
export const SELECTED_HOSPITAL_FAILURE = "SELECTED_HOSPITAL_FAILURE";

export const EXTENTION_HOSPITAL = "EXTENTION_HOSPITAL";

export const HOSPITAL_AREA_FILTER_APPLY = "HOSPITAL_AREA_FILTER_APPLY";

export const HOSPITAL_FILTER_CLEAR = "HOSPITAL_FILTER_CLEAR";

export const GET_HOSPITAL_ALL_REVIEW = "GET_HOSPITAL_ALL_REVIEW";

// Kakao Promise
export const SET_KAKAO_INFO = "SET_KAKAO_INFO";
export const SET_KAKAO_LOGIN = "SET_KAKAO_LOGIN";
export const SET_KAKAO_LOGOUT = "SET_KAKAO_LOGOUT";
export const FIXED_LOGIN = "FIXED_LOGIN";
export const LOGIN_TOKEN_CHECK = "LOGIN_TOKEN_CHECK";

// MyPage Promise
export const GET_MYHOME_INFO = "GET_MYHOME_INFO";

export const SET_FAVORITE_DOCTORS = "SET_FAVORITE_DOCTORS";
export const GET_FAVORITE_DOCTORS = "GET_FAVORITE_DOCTORS";

export const HOSPITAL_REVIEW_LIST = "HOSPITAL_REVIEW_LIST";
export const HOSPITAL_REVIEW_LIST_SUCCESS = "HOSPITAL_REVIEW_LIST_SUCCESS";
export const HOSPITAL_REVIEW_LIST_FAILURE = "HOSPITAL_REVIEW_LIST_FAILURE";

export const DOCTOR_REVIEW_LIST = "DOCTOR_REVIEW_LIST";
export const DOCTOR_REVIEW_LIST_SUCCESS = "DOCTOR_REVIEW_LIST_SUCCESS";
export const DOCTOR_REVIEW_LIST_FAILURE = "DOCTOR_REVIEW_LIST_FAILURE";

// Contact Promise
export const ASK_SEND = "ASK_SEND";
export const ASK_SEND_SUCCESS = "ASK_SEND_SUCCESS";
export const ASK_SEND_FAILURE = "ASK_SEND_FAILURE";

// Utils Promise
export const SET_MESSAGE = "SET_MESSAGE";
export const MESSAGE_OPEN = "MESSAGE_OPEN";
export const MESSAGE_CLOSE = "MESSAGE_CLOSE";

export const SET_ERROR = "SET_ERROR";
export const ERROR_OPEN = "ERROR_OPEN";
export const ERROR_CLOSE = "ERROR_CLOSE";

export const SET_WHETHER = "SET_WHETHER";
export const WHETHER_OPEN = "WHETHER_OPEN";
export const WHETHER_CLOSE = "WHETHER_CLOSE";
export const WHETHER_RESULT = "WHETHER_RESULT";

export const LOADING_OPEN = "LOADING_OPEN";
export const LOADING_CLOSE = "LOADING_CLOSE";

export const SET_COOKIE = "SET_COOKIE";
export const GET_COOKIE = "GET_COOKIE";
export const RMV_COOKIE = "RMV_COOKIE";
export const ADD_COOKIE = "ADD_COOKIE";
export const SUB_COOKIE = "SUB_COOKIE";

export const GET_COOKIE_ALL = "GET_COOKIE_ALL";
